# Generated by Django 5.0.6 on 2024-08-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='itemestoque',
            new_name='item_estoque',
        ),
    ]
