# Generated by Django 4.2.11 on 2024-12-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_pagamento_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
