# Generated by Django 5.0.6 on 2024-08-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_itemestoque_itenspedido_item_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='item_estoque',
            new_name='itemestoque',
        ),
    ]
